Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.hostname = "vagrantPy3-vm"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "vagrantPy3-vm"
        vb.customize ["modifyvm", :id, "--memory", 1024 * 2]
    end
    config.vm.provision :shell, inline: <<-SHELL
        sudo apt update
	sudo apt -y upgrade
	sudo apt install -y libpq-dev python3-dev python3-pip
	sudo pip3 install psycopg2
	sudo pip3 install django
    SHELL
    config.vm.provision :shell, inline: "mkdir -p ~/new_dir"
    config.vm.provision :file, source: "empty_file", destination: "~/new_dir/empty_file"
end
